### PR TITLE
Adding Github Actions

### PR DESCRIPTION
**Pull request by Dueel**
- Created workflow to automatically build the project

### CODE REVIEW

**Comment by Dueel** [comment]
@Polsulpicien works now

**Comment by underscorelior** [comment]
LGTM 🚀

**Review by underscorelior — COMMENTED** [review]
:nerd_face:

**Review by Zickles — APPROVED** [review]
lgtm (i hope i have green check ) :)

**Comment by Polsulpicien** [comment]
Looks good to me (except the number of commits on this PR 😄).
I've never used workflows before, what will happen once the `.exe` has been built?
It will automatically create a new release?

**Review by Polsulpicien — APPROVED** [review]

**Comment by Dueel** [comment]
Currently if a exe is built or won't do anything with it other than it be compiled.

**Comment by Polsulpicien** [comment]
Okay I see. It would maybe be a better idea to create a new release, upload the exe and then delete the exe file from the repo (if possible) since it can become a big file in the future (already 50MB)?

**Pull request merged**
